name: 'area of a rectangle'
description: 'Calculate the area of a rectangle'
icon: activity
color: #000000
inputs:
  base:
    description: 'width'
    required: true
    default: 8
  height:
    description: 'length'
    required: true
    default: 8
outputs:
  area:
    description: 'the area of the rectangle'
runs:
  using: 'node12'
  main: 'index.js'
